include(":sample:app1")
include(":sample:app2")
include(":sample:lib1a")
include(":sample:lib1b")
include(":sample:lib2a")
include(":sample:lib2b")
include(":sample:lib2c")
include(":sample:lib-shared")

include(":sample:moved")
project(":sample:moved").projectDir = File("sample/lib-moved")
